### PR TITLE
added scripts and README file for Model Based AAA

### PR DESCRIPTION
**Pull request by krishna426426**

### CODE REVIEW

**Comment by hpreston** [comment]
@krishna426426  - these look good but can you please include an update to the REPO readme that lists these new examples in the table of contents so folks know it's there and what it's purpose is.

**Comment by krishna426426** [comment]
@hpreston - Do I need to update in Main repo README file or my README file in Model-Based AAA?

**Comment by hpreston** [comment]
The main README https://github.com/CiscoDevNet/python_code_samples_network/blob/master/README.md

**Comment by krishna426426** [comment]
@hpreston - just updated. plz let me know any thing needed.

**Pull request merged**
