### PR TITLE
Update NC-get-config.py

### PR DESCRIPTION
**Pull request by cromulon-actual**
Fixed get-config arguments. Previous version resulted in error.

### CODE REVIEW

**Comment by cromulon-actual** [comment]
Previous version error:
`    raise self._reply.error
ncclient.operations.rpc.RPCError: {'type': 'protocol', 'tag': 'unknown-element', 'app_tag': None, 'severity': 'error', 'info': '<?xml version="1.0" encoding="UTF-8"?><error-info xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><bad-element>filter</bad-element>\n</error-info>\n', 'path': '\n    /rpc/get-config\n  ', 'message': None}`

**Comment by xorrkaz** [comment]
Hmmm, the original works for me on recent IOS-XE.  What device and version are you using?  Admittedly, the variable name lends itself to just return the hostname, but I'm not inclined to change the code as doing a subtree filter (or seeing it done) is useful.

**Comment by cromulon-actual** [comment]
I used the always on iosxe sandbox on decent.

**Comment by einarnn** [comment]
> Hmmm, the original works for me on recent IOS-XE.  What device and version are you using?  Admittedly, the variable name lends itself to just return the hostname, but I'm not inclined to change the code as doing a subtree filter (or seeing it done) is useful.

Recent versions of IOS XE have stopped making netconf base the default namespace for netconf messages. This means you need to set the namespace for `filter`, rather than assume that XE will do that,n as it has done in the past. An alternative to that is to use the form of get similar to the xpath example, passing `subtree` instead. In that form, the filter you pass in should leave out the `filter` tag, making your code insensitive to this issue.

Cheers,

Einar

**Comment by xorrkaz** [comment]
Thanks, Einar!  I hadn't realized DevNet updated their Sandbox image to 17.3.  I'm still back on 16.12 at home.  I added the NS to filter, since I think it's best to be explicit and show people that namespaces matter.  Thanks, @cromulon-actual for the report!

**Comment by cromulon-actual** [comment]
No problem! Though I stumbled upon this, there may be revisions needed in other script examples in the repo.

**Comment by xorrkaz** [comment]
Yeah, I found cases in a couple of other scripts which I fixed.

**Pull request closed without merging**
